sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"

env:
  - WEBPACK_VERSION=1
  - WEBPACK_VERSION=2

matrix:
  fast_finish: true
before_install:
  - nvm --version
  - node --version
  - npm --version
before_script:
  - "npm install webpack@$WEBPACK_VERSION"
script:
  - npm run cover

after_success:
 - bash <(curl -s https://codecov.io/bash)
